TYPE=VIEW
query=select `ms`.`merc_npc_type_id` AS `merc_npc_type_id`,\'\' AS `name`,`ms`.`clientlevel` AS `clientlevel`,`ms`.`level` AS `level`,`mtyp`.`race_id` AS `race_id`,`mstyp`.`class_id` AS `class_id`,`ms`.`hp` AS `hp`,`ms`.`mana` AS `mana`,0 AS `gender`,`mai`.`texture` AS `texture`,`mai`.`helmtexture` AS `helmtexture`,`ms`.`attack_speed` AS `attack_speed`,`ms`.`STR` AS `STR`,`ms`.`STA` AS `STA`,`ms`.`DEX` AS `DEX`,`ms`.`AGI` AS `AGI`,`ms`.`_INT` AS `_INT`,`ms`.`WIS` AS `WIS`,`ms`.`CHA` AS `CHA`,`ms`.`MR` AS `MR`,`ms`.`CR` AS `CR`,`ms`.`DR` AS `DR`,`ms`.`FR` AS `FR`,`ms`.`PR` AS `PR`,`ms`.`Corrup` AS `Corrup`,`ms`.`mindmg` AS `mindmg`,`ms`.`maxdmg` AS `maxdmg`,`ms`.`attack_count` AS `attack_count`,`ms`.`special_abilities` AS `special_abilities`,`mwi`.`d_melee_texture1` AS `d_melee_texture1`,`mwi`.`d_melee_texture2` AS `d_melee_texture2`,`mwi`.`prim_melee_type` AS `prim_melee_type`,`mwi`.`sec_melee_type` AS `sec_melee_type`,`ms`.`runspeed` AS `runspeed`,`ms`.`hp_regen_rate` AS `hp_regen_rate`,`ms`.`mana_regen_rate` AS `mana_regen_rate`,1 AS `bodytype`,`mai`.`armortint_id` AS `armortint_id`,`mai`.`armortint_red` AS `armortint_red`,`mai`.`armortint_green` AS `armortint_green`,`mai`.`armortint_blue` AS `armortint_blue`,`ms`.`AC` AS `AC`,`ms`.`ATK` AS `ATK`,`ms`.`Accuracy` AS `Accuracy`,`ms`.`spellscale` AS `spellscale`,`ms`.`healscale` AS `healscale` from (((((`peq`.`merc_stats` `ms` join `peq`.`merc_armorinfo` `mai` on(((`ms`.`merc_npc_type_id` = `mai`.`merc_npc_type_id`) and (`mai`.`minlevel` <= `ms`.`level`) and (`mai`.`maxlevel` >= `ms`.`level`)))) join `peq`.`merc_weaponinfo` `mwi` on(((`ms`.`merc_npc_type_id` = `mwi`.`merc_npc_type_id`) and (`mwi`.`minlevel` <= `ms`.`level`) and (`mwi`.`maxlevel` >= `ms`.`level`)))) join `peq`.`merc_templates` `mtem` on((`mtem`.`merc_npc_type_id` = `ms`.`merc_npc_type_id`))) join `peq`.`merc_types` `mtyp` on((`mtem`.`merc_type_id` = `mtyp`.`merc_type_id`))) join `peq`.`merc_subtypes` `mstyp` on((`mtem`.`merc_subtype_id` = `mstyp`.`merc_subtype_id`)))
md5=d7ff19192095c595cc00ee20d03fd693
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2019-06-07 06:54:22
create-version=2
source=SELECT\n	ms.merc_npc_type_id,\n	\'\' AS name,\n	ms.clientlevel,\n	ms.level,\n	mtyp.race_id,\n	mstyp.class_id,\n	ms.hp,\n	ms.mana,\n	0 AS gender,\n	mai.texture,\n	mai.helmtexture,\n	ms.attack_speed,\n	ms.STR,\n	ms.STA,\n	ms.DEX,\n	ms.AGI,\n	ms._INT,\n	ms.WIS,\n	ms.CHA,\n	ms.MR,\n	ms.CR,\n	ms.DR,\n	ms.FR,\n	ms.PR,\n	ms.Corrup,\n	ms.mindmg,\n	ms.maxdmg,\n	ms.attack_count,\n	ms.special_abilities AS special_abilities,\n	mwi.d_melee_texture1,\n	mwi.d_melee_texture2,\n	mwi.prim_melee_type,\n	mwi.sec_melee_type,\n	ms.runspeed,\n	ms.hp_regen_rate,\n	ms.mana_regen_rate,\n	1 AS bodytype,\n	mai.armortint_id,\n	mai.armortint_red,\n	mai.armortint_green,\n	mai.armortint_blue,\n	ms.AC,\n	ms.ATK,\n	ms.Accuracy,\n	ms.spellscale,\n	ms.healscale\nFROM merc_stats ms\nINNER JOIN merc_armorinfo mai\nON ms.merc_npc_type_id = mai.merc_npc_type_id\nAND mai.minlevel <= ms.level AND mai.maxlevel >= ms.level\nINNER JOIN merc_weaponinfo mwi\nON ms.merc_npc_type_id = mwi.merc_npc_type_id\nAND mwi.minlevel <= ms.level AND mwi.maxlevel >= ms.level\nINNER JOIN merc_templates mtem\nON mtem.merc_npc_type_id = ms.merc_npc_type_id\nINNER JOIN merc_types mtyp\nON mtem.merc_type_id = mtyp.merc_type_id\nINNER JOIN merc_subtypes mstyp\nON mtem.merc_subtype_id = mstyp.merc_subtype_id
client_cs_name=cp850
connection_cl_name=cp850_general_ci
view_body_utf8=select `ms`.`merc_npc_type_id` AS `merc_npc_type_id`,\'\' AS `name`,`ms`.`clientlevel` AS `clientlevel`,`ms`.`level` AS `level`,`mtyp`.`race_id` AS `race_id`,`mstyp`.`class_id` AS `class_id`,`ms`.`hp` AS `hp`,`ms`.`mana` AS `mana`,0 AS `gender`,`mai`.`texture` AS `texture`,`mai`.`helmtexture` AS `helmtexture`,`ms`.`attack_speed` AS `attack_speed`,`ms`.`STR` AS `STR`,`ms`.`STA` AS `STA`,`ms`.`DEX` AS `DEX`,`ms`.`AGI` AS `AGI`,`ms`.`_INT` AS `_INT`,`ms`.`WIS` AS `WIS`,`ms`.`CHA` AS `CHA`,`ms`.`MR` AS `MR`,`ms`.`CR` AS `CR`,`ms`.`DR` AS `DR`,`ms`.`FR` AS `FR`,`ms`.`PR` AS `PR`,`ms`.`Corrup` AS `Corrup`,`ms`.`mindmg` AS `mindmg`,`ms`.`maxdmg` AS `maxdmg`,`ms`.`attack_count` AS `attack_count`,`ms`.`special_abilities` AS `special_abilities`,`mwi`.`d_melee_texture1` AS `d_melee_texture1`,`mwi`.`d_melee_texture2` AS `d_melee_texture2`,`mwi`.`prim_melee_type` AS `prim_melee_type`,`mwi`.`sec_melee_type` AS `sec_melee_type`,`ms`.`runspeed` AS `runspeed`,`ms`.`hp_regen_rate` AS `hp_regen_rate`,`ms`.`mana_regen_rate` AS `mana_regen_rate`,1 AS `bodytype`,`mai`.`armortint_id` AS `armortint_id`,`mai`.`armortint_red` AS `armortint_red`,`mai`.`armortint_green` AS `armortint_green`,`mai`.`armortint_blue` AS `armortint_blue`,`ms`.`AC` AS `AC`,`ms`.`ATK` AS `ATK`,`ms`.`Accuracy` AS `Accuracy`,`ms`.`spellscale` AS `spellscale`,`ms`.`healscale` AS `healscale` from (((((`peq`.`merc_stats` `ms` join `peq`.`merc_armorinfo` `mai` on(((`ms`.`merc_npc_type_id` = `mai`.`merc_npc_type_id`) and (`mai`.`minlevel` <= `ms`.`level`) and (`mai`.`maxlevel` >= `ms`.`level`)))) join `peq`.`merc_weaponinfo` `mwi` on(((`ms`.`merc_npc_type_id` = `mwi`.`merc_npc_type_id`) and (`mwi`.`minlevel` <= `ms`.`level`) and (`mwi`.`maxlevel` >= `ms`.`level`)))) join `peq`.`merc_templates` `mtem` on((`mtem`.`merc_npc_type_id` = `ms`.`merc_npc_type_id`))) join `peq`.`merc_types` `mtyp` on((`mtem`.`merc_type_id` = `mtyp`.`merc_type_id`))) join `peq`.`merc_subtypes` `mstyp` on((`mtem`.`merc_subtype_id` = `mstyp`.`merc_subtype_id`)))
mariadb-version=100021
